test.build zstd 1

diff --git a/.github/workflows/toolchain-build.yml b/.github/workflows/toolchain-build.yml
--- a/.github/workflows/toolchain-build.yml
+++ b/.github/workflows/toolchain-build.yml
@@ -356,8 +356,145 @@ jobs:
 
           echo "Downloaded prerequisites!"
           curl -s -X POST "https://api.telegram.org/bot${{ env.BOT_TOKEN }}/sendMessage" -d chat_id="${{ env.CHAT_ID }}" -d "disable_web_page_preview=true" -d "parse_mode=html" -d text="<b>Starting centos7 GCC Build</b>"
-          cd "${WORK_DIR}"
+          
+          # --------- build zstd -----------------
+          COMPOMENTS_ZSTD_VERSION=1.5.7
+          PREFIX_DIR="$PREFIX"
+          PREFIX_BASE_NAME="$(basename "$PREFIX")"
+          BUILD_STAGE1_LIBRARY_PREFIX="$WORKING_DIR/stage1-$PREFIX_BASE_NAME-library"
+          BUILD_STAGE1_TOOLS_PREFIX="$WORKING_DIR/stage1-$PREFIX_BASE_NAME-tools"
+          BUILD_STAGE1_GCC_PREFIX="$WORKING_DIR/stage1-$PREFIX_BASE_NAME-gcc"
+          # ======================= 统一的包检查和下载函数 =======================
+          function check_and_download() {
+            PKG_NAME="$1"
+            PKG_MATCH_EXPR="$2"
+            PKG_URL="$3"
 
+            PKG_VAR_VAL=($(find . -maxdepth 1 -type f -name "$PKG_MATCH_EXPR"))
+            if [[ ${#PKG_VAR_VAL[@]} -gt 0 ]]; then
+              echo "${PKG_VAR_VAL[0]}"
+              return 0
+            fi
+
+            if [[ -z "$PKG_URL" ]]; then
+              echo -e "\\033[31;1m$PKG_NAME not found.\\033[39;49;0m"
+              return 1
+            fi
+
+            if [[ -z "$4" ]]; then
+              OUTPUT_FILE="$(basename "$PKG_URL")"
+            else
+              OUTPUT_FILE="$4"
+            fi
+
+            DOWNLOAD_SUCCESS=1
+            for ((i = 0; i < 5; ++i)); do
+              if [[ $DOWNLOAD_SUCCESS -eq 0 ]]; then
+                break
+              fi
+              DOWNLOAD_SUCCESS=0
+              if [[ $i -ne 0 ]]; then
+                echo "Retry to download from $PKG_URL to $OUTPUT_FILE again."
+                sleep $i || true
+              fi
+              curl -kL "$PKG_URL" -o "$OUTPUT_FILE" || DOWNLOAD_SUCCESS=1
+            done
+
+            if [[ $DOWNLOAD_SUCCESS -ne 0 ]]; then
+              echo -e "\\033[31;1mDownload $PKG_NAME from $PKG_URL failed.\\033[39;49;0m"
+              rm -f "$OUTPUT_FILE" || true
+              return $DOWNLOAD_SUCCESS
+            fi
+
+            PKG_VAR_VAL=($(find . -maxdepth 1 -name "$PKG_MATCH_EXPR"))
+
+            if [[ ${#PKG_VAR_VAL} -eq 0 ]]; then
+              echo -e "\\033[31;1m$PKG_NAME not found.\\033[39;49;0m"
+              return 1
+            fi
+
+            echo "${PKG_VAR_VAL[0]}"
+          }
+          
+          # install zstd
+          function build_zstd() {
+            INSTALL_PREFIX_PATH="$1"
+            STAGE_CFLAGS=""
+            STAGE_LDFLAGS=""
+            if [[ "$INSTALL_PREFIX_PATH" == "$BUILD_STAGE1_LIBRARY_PREFIX" ]] || [[ "$INSTALL_PREFIX_PATH" == "$BUILD_STAGE1_TOOLS_PREFIX" ]]; then
+              STAGE_CONFIGURE_OPTIONS="-DBUILD_SHARED_LIBS=OFF "
+              BUILD_BACKUP_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
+              if [[ "x$BUILD_BACKUP_PKG_CONFIG_PATH" == "x" ]]; then
+                export PKG_CONFIG_PATH="$BUILD_STAGE1_LIBRARY_PREFIX/lib64/pkgconfig:$BUILD_STAGE1_LIBRARY_PREFIX/lib/pkgconfig"
+              else
+                export PKG_CONFIG_PATH="$BUILD_STAGE1_LIBRARY_PREFIX/lib64/pkgconfig:$BUILD_STAGE1_LIBRARY_PREFIX/lib/pkgconfig:$BUILD_BACKUP_PKG_CONFIG_PATH"
+              fi
+              STAGE_CFLAGS="-I$BUILD_STAGE1_LIBRARY_PREFIX/include "
+              STAGE_LDFLAGS="-L$BUILD_STAGE1_LIBRARY_PREFIX/lib64 -L$BUILD_STAGE1_LIBRARY_PREFIX/lib "
+            else
+              STAGE_CONFIGURE_OPTIONS="-DBUILD_SHARED_LIBS=ON "
+              STAGE_CFLAGS="-I$INSTALL_PREFIX_PATH/include "
+              STAGE_LDFLAGS="-L$INSTALL_PREFIX_PATH/lib64 -L$INSTALL_PREFIX_PATH/lib "
+            fi
+
+            echo "$LDFLAGS" | grep -F '$ORIGIN/../lib64' || STAGE_LDFLAGS="$STAGE_LDFLAGS -Wl,-rpath=\$ORIGIN:\$ORIGIN/../lib64:\$ORIGIN/../lib"
+
+            if [[ -z "$BUILD_TARGET_COMPOMENTS" ]] || [[ "0" == $(is_in_list zstd $BUILD_TARGET_COMPOMENTS) ]]; then
+              ZSTD_PKG=$(check_and_download "zstd" "zstd-$COMPOMENTS_ZSTD_VERSION*.tar.gz" "$REPOSITORY_MIRROR_URL_GITHUB/facebook/zstd/releases/download/v$COMPOMENTS_ZSTD_VERSION/zstd-$COMPOMENTS_ZSTD_VERSION.tar.gz" "zstd-$COMPOMENTS_ZSTD_VERSION.tar.gz")
+              if [[ $? -ne 0 ]]; then
+                echo -e "$ZSTD_PKG"
+                exit 1
+              fi
+              if [[ $BUILD_DOWNLOAD_ONLY -eq 0 ]]; then
+                tar -axvf $ZSTD_PKG
+                ZSTD_DIR=$(ls -d zstd-$COMPOMENTS_ZSTD_VERSION* | grep -v \.tar\.gz)
+                cd $ZSTD_DIR
+                mkdir -p build_jobs_dir
+                cd build_jobs_dir
+
+                if [[ -e CMakeCache.txt ]]; then
+                  cmake --build . --target clean
+                  rm -f CMakeCache.txt
+                fi
+
+                # Using -DCMAKE_INSTALL_LIBDIR=lib to keep the same output directory as configure settings
+                env LDFLAGS="${STAGE_LDFLAGS}${LDFLAGS}" CFLAGS="${STAGE_CFLAGS}${CFLAGS}" CXXFLAGS="${STAGE_CFLAGS}${CXXFLAGS}" \
+                  cmake ../build/cmake "-DCMAKE_POSITION_INDEPENDENT_CODE=ON" "-DZSTD_BUILD_TESTS=OFF" "-DZSTD_BUILD_CONTRIB=0" "-DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX_PATH" \
+                  -DCMAKE_INSTALL_LIBDIR=lib \
+                  "-DCMAKE_FIND_ROOT_PATH=$INSTALL_PREFIX_PATH" "-DCMAKE_PREFIX_PATH=$INSTALL_PREFIX_PATH" $STAGE_CONFIGURE_OPTIONS
+                if [[ $? -ne 0 ]]; then
+                  echo -e "\\033[31;1mError: configure zstd failed.\\033[39;49;0m"
+                  exit 1
+                fi
+
+                env LDFLAGS="${STAGE_LDFLAGS}${LDFLAGS}" CFLAGS="${STAGE_CFLAGS}${CFLAGS}" CXXFLAGS="${STAGE_CFLAGS}${CXXFLAGS}" \
+                  cmake --build . $BUILD_THREAD_OPT
+                if [[ $? -ne 0 ]]; then
+                  echo -e "\\033[31;1mError: build zstd failed.\\033[39;49;0m"
+                  exit 1
+                fi
+
+                env LDFLAGS="${STAGE_LDFLAGS}${LDFLAGS}" CFLAGS="${STAGE_CFLAGS}${CFLAGS}" CXXFLAGS="${STAGE_CFLAGS}${CXXFLAGS}" \
+                  cmake --install . --prefix "$INSTALL_PREFIX_PATH"
+
+                if [[ $? -ne 0 ]]; then
+                  echo -e "\\033[31;1mError: install zstd failed.\\033[39;49;0m"
+                  exit 1
+                fi
+
+                cd "$WORKING_DIR"
+              fi
+            fi
+          }
+          # Prepare directories
+          # bootstrap
+          mkdir -p "$PREFIX_DIR/include"
+          mkdir -p "$PREFIX_DIR/lib"
+          mkdir -p "$PREFIX_DIR/lib64"
+
+          build_zstd "$PREFIX_DIR"
+          
+          cd "${WORK_DIR}"
           echo "Building Binutils"
           mkdir build-binutils
           cd build-binutils
@@ -375,15 +512,21 @@ jobs:
               --enable-gold \
               --enable-deterministic-archives=no \
               --enable-lto \
+              --enable-libada \
               --enable-compressed-debug-sections=none \
               --enable-generate-build-notes=no \
               --enable-threads=yes \
               --enable-relro=yes \
               --enable-plugins \
+              --enable-build-with-cxx \
+              --enable-host-pie \
               --prefix="$PREFIX" \
               --with-bugurl=https://github.com/indiff/gcc-build \
               --with-sysroot=/  \
               --with-pkgversion="Indiff binutils"
+          
+          # Patch for binutils 2.39(gprofng's documents have some error when building)
+          sed -i.bak 's/[[:space:]]doc$//g' ../gprofng/Makefile.in
               
           make -j"$JOBS"
           make install -j"$JOBS"
@@ -418,7 +561,7 @@ jobs:
           rm -rf ../gcc/testsuite
           # tree "${VCPKG_ROOT}/packages/zstd_x64-linux/"
           yum install -y libzstd-devel libzstd 
-          env CFLAGS="$OPT_FLAGS -I/usr/include" CXXFLAGS="$OPT_FLAGS -I/usr/include" \
+          env LDFLAGS="-Wl,-rpath=$PREFIX/lib64:$PREFIX/lib" CFLAGS="$OPT_FLAGS -fPIC -I$PREFIX/include " CXXFLAGS="$OPT_FLAGS -fPIC -I$PREFIX/include " \
             ../gcc/configure --target="$TARGET" --build="$TARGET" --host="$TARGET" \
             --with-bugurl=https://github.com/indiff/gcc-build \
             --disable-decimal-float \
